package com.zwxu.lc.um.model;

public class Menu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.menu_name
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	private String menuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.menu_url
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	private String menuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.role_id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.parent_id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.status
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.id
	 * @return  the value of t_menu.id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.id
	 * @param id  the value for t_menu.id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.menu_name
	 * @return  the value of t_menu.menu_name
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.menu_name
	 * @param menuName  the value for t_menu.menu_name
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.menu_url
	 * @return  the value of t_menu.menu_url
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public String getMenuUrl() {
		return menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.menu_url
	 * @param menuUrl  the value for t_menu.menu_url
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.role_id
	 * @return  the value of t_menu.role_id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.role_id
	 * @param roleId  the value for t_menu.role_id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.parent_id
	 * @return  the value of t_menu.parent_id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.parent_id
	 * @param parentId  the value for t_menu.parent_id
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.status
	 * @return  the value of t_menu.status
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.status
	 * @param status  the value for t_menu.status
	 * @mbggenerated  Mon Nov 28 13:57:39 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}