package com.zwxu.lc.um.model;

public class MenuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.menu_id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.role_id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.id
     *
     * @return the value of t_menu_role.id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.id
     *
     * @param id the value for t_menu_role.id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.menu_id
     *
     * @return the value of t_menu_role.menu_id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.menu_id
     *
     * @param menuId the value for t_menu_role.menu_id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.role_id
     *
     * @return the value of t_menu_role.role_id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.role_id
     *
     * @param roleId the value for t_menu_role.role_id
     *
     * @mbggenerated Mon Nov 28 10:44:28 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}