package com.zwxu.lc.um.model;

public class Menu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.id
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.menu_name
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	private String menuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.menu_url
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	private String menuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.parent_id
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.delete_flag
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	private String deleteFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.id
	 * @return  the value of t_menu.id
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.id
	 * @param id  the value for t_menu.id
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.menu_name
	 * @return  the value of t_menu.menu_name
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.menu_name
	 * @param menuName  the value for t_menu.menu_name
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.menu_url
	 * @return  the value of t_menu.menu_url
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public String getMenuUrl() {
		return menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.menu_url
	 * @param menuUrl  the value for t_menu.menu_url
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.parent_id
	 * @return  the value of t_menu.parent_id
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.parent_id
	 * @param parentId  the value for t_menu.parent_id
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.delete_flag
	 * @return  the value of t_menu.delete_flag
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.delete_flag
	 * @param deleteFlag  the value for t_menu.delete_flag
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
}