package com.zwxu.lc.um.model;

import java.util.Date;

public class MenuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.id
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.mid
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.rid
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.created_time
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.id
     *
     * @return the value of t_menu_role.id
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.id
     *
     * @param id the value for t_menu_role.id
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.mid
     *
     * @return the value of t_menu_role.mid
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.mid
     *
     * @param mid the value for t_menu_role.mid
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.rid
     *
     * @return the value of t_menu_role.rid
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.rid
     *
     * @param rid the value for t_menu_role.rid
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.created_time
     *
     * @return the value of t_menu_role.created_time
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.created_time
     *
     * @param createdTime the value for t_menu_role.created_time
     *
     * @mbggenerated Mon Jan 09 20:10:22 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}