package com.zwxu.lc.um.model;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.id
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.role_code
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	private String roleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.role_name
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.gmt_created
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	private Date gmtCreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.gmt_modify
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	private Date gmtModify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.delete_flag
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	private String deleteFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.id
	 * @return  the value of t_role.id
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.id
	 * @param id  the value for t_role.id
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.role_code
	 * @return  the value of t_role.role_code
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public String getRoleCode() {
		return roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.role_code
	 * @param roleCode  the value for t_role.role_code
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.role_name
	 * @return  the value of t_role.role_name
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.role_name
	 * @param roleName  the value for t_role.role_name
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.gmt_created
	 * @return  the value of t_role.gmt_created
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public Date getGmtCreated() {
		return gmtCreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.gmt_created
	 * @param gmtCreated  the value for t_role.gmt_created
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.gmt_modify
	 * @return  the value of t_role.gmt_modify
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public Date getGmtModify() {
		return gmtModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.gmt_modify
	 * @param gmtModify  the value for t_role.gmt_modify
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.delete_flag
	 * @return  the value of t_role.delete_flag
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.delete_flag
	 * @param deleteFlag  the value for t_role.delete_flag
	 * @mbggenerated  Tue Jan 10 13:17:24 CST 2017
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
}