package com.zwxu.lc.um.model;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.username
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.number
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.groupid
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.aid
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.pass_count
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private Integer passCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.reject_count
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private Integer rejectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.status
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.create_time
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.username
     *
     * @return the value of t_student.username
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.username
     *
     * @param username the value for t_student.username
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school
     *
     * @return the value of t_student.school
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school
     *
     * @param school the value for t_student.school
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.number
     *
     * @return the value of t_student.number
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.number
     *
     * @param number the value for t_student.number
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.groupid
     *
     * @return the value of t_student.groupid
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.groupid
     *
     * @param groupid the value for t_student.groupid
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.aid
     *
     * @return the value of t_student.aid
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.aid
     *
     * @param aid the value for t_student.aid
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.pass_count
     *
     * @return the value of t_student.pass_count
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public Integer getPassCount() {
        return passCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.pass_count
     *
     * @param passCount the value for t_student.pass_count
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setPassCount(Integer passCount) {
        this.passCount = passCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.reject_count
     *
     * @return the value of t_student.reject_count
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public Integer getRejectCount() {
        return rejectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.reject_count
     *
     * @param rejectCount the value for t_student.reject_count
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setRejectCount(Integer rejectCount) {
        this.rejectCount = rejectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.status
     *
     * @return the value of t_student.status
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.status
     *
     * @param status the value for t_student.status
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.create_time
     *
     * @return the value of t_student.create_time
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.create_time
     *
     * @param createTime the value for t_student.create_time
     *
     * @mbggenerated Sat Nov 26 15:40:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}