package com.zwxu.lc.um.model;

import java.util.Date;

public class Teacher {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_teacher.id
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_teacher.username
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_teacher.department
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_teacher.aid
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	private Integer aid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_teacher.created_time
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	private Date createdTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_teacher.id
	 * @return  the value of t_teacher.id
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_teacher.id
	 * @param id  the value for t_teacher.id
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_teacher.username
	 * @return  the value of t_teacher.username
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_teacher.username
	 * @param username  the value for t_teacher.username
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_teacher.department
	 * @return  the value of t_teacher.department
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_teacher.department
	 * @param department  the value for t_teacher.department
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_teacher.aid
	 * @return  the value of t_teacher.aid
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public Integer getAid() {
		return aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_teacher.aid
	 * @param aid  the value for t_teacher.aid
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_teacher.created_time
	 * @return  the value of t_teacher.created_time
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_teacher.created_time
	 * @param createdTime  the value for t_teacher.created_time
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}
}