package com.zwxu.lc.um.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.school
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.groupid
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.tid
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.pass_count
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private Integer passCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.reject_count
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private Integer rejectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.school
     *
     * @return the value of t_user.school
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.school
     *
     * @param school the value for t_user.school
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.groupid
     *
     * @return the value of t_user.groupid
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.groupid
     *
     * @param groupid the value for t_user.groupid
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.tid
     *
     * @return the value of t_user.tid
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.tid
     *
     * @param tid the value for t_user.tid
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.pass_count
     *
     * @return the value of t_user.pass_count
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public Integer getPassCount() {
        return passCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.pass_count
     *
     * @param passCount the value for t_user.pass_count
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setPassCount(Integer passCount) {
        this.passCount = passCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.reject_count
     *
     * @return the value of t_user.reject_count
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public Integer getRejectCount() {
        return rejectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.reject_count
     *
     * @param rejectCount the value for t_user.reject_count
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setRejectCount(Integer rejectCount) {
        this.rejectCount = rejectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbggenerated Sat Nov 19 12:19:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}