package com.zwxu.lc.um.mapper;

import com.zwxu.lc.um.model.Menu;
import java.util.List;
import com.zwxu.lc.um.model.MenuExample;
import org.apache.ibatis.annotations.Param;



public interface MenuMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int countByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int deleteByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int insert(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int insertSelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	List<Menu> selectByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	Menu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Menu record,
			@Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int updateByExample(@Param("record") Menu record,
			@Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu
	 * @mbggenerated  Tue Jan 10 13:16:57 CST 2017
	 */
	int updateByPrimaryKey(Menu record);

	List<Menu> selectMenuByRoleId(int roleId);
}