package com.zwxu.lc.um.mapper;

import java.util.List;
import com.zwxu.lc.um.model.MenuRole;
import com.zwxu.lc.um.model.MenuRoleExample;
import org.apache.ibatis.annotations.Param;

public interface MenuRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int countByExample(MenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int deleteByExample(MenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int insert(MenuRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int insertSelective(MenuRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	List<MenuRole> selectByExample(MenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	MenuRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int updateByExampleSelective(@Param("record") MenuRole record,
			@Param("example") MenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int updateByExample(@Param("record") MenuRole record,
			@Param("example") MenuRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int updateByPrimaryKeySelective(MenuRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_menu_role
	 * @mbggenerated  Mon Jan 09 20:10:22 CST 2017
	 */
	int updateByPrimaryKey(MenuRole record);

	List<Integer> selectMenuByRoleId(int roleId);
}