package com.zwxu.lc.um.mapper;

import com.zwxu.lc.um.model.Teacher;
import com.zwxu.lc.um.model.TeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	int countByExample(TeacherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	int deleteByExample(TeacherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	int insert(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	int insertSelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	List<Teacher> selectByExample(TeacherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Teacher record,
			@Param("example") TeacherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_teacher
	 * @mbggenerated  Mon Jan 09 22:53:19 CST 2017
	 */
	int updateByExample(@Param("record") Teacher record,
			@Param("example") TeacherExample example);
}